apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  {{- range .Values.configMap }}
  {{ .key }}: "{{ .value }}"
  {{- end }}
